### PR TITLE
add point type

### PR DESCRIPTION
**Pull request by Dhruvit96**
## Summary
Add support for Point type.
Closes https://github.com/ClickHouse/clickhouse-connect/issues/151

## Checklist
Delete items not relevant to your PR:
- [x] Unit and integration tests covering the common scenarios were added
- [x] A human-readable description of the changes was provided to include in CHANGELOG

### CODE REVIEW

**Comment by genzgd** [comment]
Thanks for the PR!

I'm a little concerned about the implementation of converting `Point` to a `Tuple(Float64, Float64)`.  It looks like ClickHouse actually sends `Point` as the type:  
```
CREATE TABLE points
(
    `key` UInt32,
    `value` Point
)
ENGINE = MergeTree
ORDER BY key

INSERT INTO points VALUES(1, (5.22, 7.83));

clickhouse client --port 9007 --query "SELECT * from points FORMAT Native" | xxd

00000000: 0201 036b 6579 0655 496e 7433 3201 0000  ...key.UInt32...
00000010: 0005 7661 6c75 6505 506f 696e 74e1 7a14  ..value.Point.z.
00000020: ae47 e114 4052 b81e 85eb 511f 40         .G..@R....Q.@
```

It seems we should be consistent and use the `Point` name when doing inserts as well, and for that approach I think it makes more sense to make a `Point` datatypes that extends  `clickhouse_connect.datatypes.containers.Tuple`.

We probably should have at least one integration test as well.

**Comment by Dhruvit96** [comment]
> Thanks for the PR!
> 
> I'm a little concerned about the implementation of converting `Point` to a `Tuple(Float64, Float64)`. It looks like ClickHouse actually sends `Point` as the type:
> 
> ```
> CREATE TABLE points
> (
>     `key` UInt32,
>     `value` Point
> )
> ENGINE = MergeTree
> ORDER BY key
> 
> INSERT INTO points VALUES(1, (5.22, 7.83));
> 
> clickhouse client --port 9007 --query "SELECT * from points FORMAT Native" | xxd
> 
> 00000000: 0201 036b 6579 0655 496e 7433 3201 0000  ...key.UInt32...
> 00000010: 0005 7661 6c75 6505 506f 696e 74e1 7a14  ..value.Point.z.
> 00000020: ae47 e114 4052 b81e 85eb 511f 40         .G..@R....Q.@
> ```
> 
> It seems we should be consistent and use the `Point` name when doing inserts as well, and for that approach I think it makes more sense to make a `Point` datatypes that extends `clickhouse_connect.datatypes.containers.Tuple`.
> 
> We probably should have at least one integration test as well.

Hello, I'm still new to this can you 

> Thanks for the PR!
> 
> I'm a little concerned about the implementation of converting `Point` to a `Tuple(Float64, Float64)`. It looks like ClickHouse actually sends `Point` as the type:
> 
> ```
> CREATE TABLE points
> (
>     `key` UInt32,
>     `value` Point
> )
> ENGINE = MergeTree
> ORDER BY key
> 
> INSERT INTO points VALUES(1, (5.22, 7.83));
> 
> clickhouse client --port 9007 --query "SELECT * from points FORMAT Native" | xxd
> 
> 00000000: 0201 036b 6579 0655 496e 7433 3201 0000  ...key.UInt32...
> 00000010: 0005 7661 6c75 6505 506f 696e 74e1 7a14  ..value.Point.z.
> 00000020: ae47 e114 4052 b81e 85eb 511f 40         .G..@R....Q.@
> ```
> 
> It seems we should be consistent and use the `Point` name when doing inserts as well, and for that approach I think it makes more sense to make a `Point` datatypes that extends `clickhouse_connect.datatypes.containers.Tuple`.
> 
> We probably should have at least one integration test as well.

I have added Point type in container.py and also added one integration test.
Please let me know if any change is required.

**Comment by Dhruvit96** [comment]
Hi can you please help me debug issue here.
I'm not sure why it's failing.

**Comment by genzgd** [comment]
The failure is not related to your PR, it's something in the test setup.  I'll figure it out in the next day or so.

**Comment by Dhruvit96** [comment]
> The failure is not related to your PR, it's something in the test setup. I'll figure it out in the next day or so.

Meanwhile please let me know if any changes in required in code.

**Comment by Dhruvit96** [comment]
Thank you for quick review!!

**Pull request merged**
